
const kanjiData = {
  N5: [
    // Numbers (16)
    { kanji: "一", reading: "いち", english: "one" },
    { kanji: "二", reading: "に", english: "two" },
    { kanji: "三", reading: "さん", english: "three" },
    { kanji: "四", reading: "し", english: "four" },
    { kanji: "五", reading: "ご", english: "five" },
    { kanji: "六", reading: "ろく", english: "six" },
    { kanji: "七", reading: "しち", english: "seven" },
    { kanji: "八", reading: "はち", english: "eight" },
    { kanji: "九", reading: "きゅう", english: "nine" },
    { kanji: "十", reading: "じゅう", english: "ten" },
    { kanji: "百", reading: "ひゃく", english: "hundred" },
    { kanji: "千", reading: "せん", english: "thousand" },
    { kanji: "万", reading: "まん", english: "ten thousand" },
    { kanji: "円", reading: "えん", english: "yen" },
    { kanji: "週", reading: "しゅう", english: "week" },
    { kanji: "分", reading: "ふん", english: "minute" },

    // Time (16)
    { kanji: "日", reading: "にち", english: "day" },
    { kanji: "月", reading: "がつ", english: "month" },
    { kanji: "年", reading: "ねん", english: "year" },
    { kanji: "時", reading: "じ", english: "time" },
    { kanji: "間", reading: "かん", english: "interval" },
    { kanji: "午", reading: "ご", english: "noon" },
    { kanji: "前", reading: "まえ", english: "before" },
    { kanji: "後", reading: "あと", english: "after" },
    { kanji: "今", reading: "いま", english: "now" },
    { kanji: "先", reading: "さき", english: "previous" },
    { kanji: "来", reading: "く", english: "to come" },
    { kanji: "半", reading: "はん", english: "half" },
    { kanji: "毎", reading: "まい", english: "every" },
    { kanji: "何", reading: "なに", english: "what" },
    { kanji: "午前", reading: "ごぜん", english: "A.M." },
    { kanji: "午後", reading: "ごご", english: "P.M." },

    // People & Things (31)
    { kanji: "人", reading: "ひと", english: "person" },
    { kanji: "男", reading: "おとこ", english: "man" },
    { kanji: "女", reading: "おんな", english: "woman" },
    { kanji: "子", reading: "こ", english: "child" },
    { kanji: "母", reading: "はは", english: "mother" },
    { kanji: "父", reading: "ちち", english: "father" },
    { kanji: "友", reading: "とも", english: "friend" },
    { kanji: "火", reading: "ひ", english: "fire" },
    { kanji: "水", reading: "みず", english: "water" },
    { kanji: "木", reading: "き", english: "tree" },
    { kanji: "土", reading: "つち", english: "earth" },
    { kanji: "金", reading: "かね", english: "gold" },
    { kanji: "本", reading: "ほん", english: "book" },
    { kanji: "川", reading: "かわ", english: "river" },
    { kanji: "花", reading: "はな", english: "flower" },
    { kanji: "気", reading: "き", english: "spirit" },
    { kanji: "生", reading: "いきる", english: "life" },
    { kanji: "魚", reading: "さかな", english: "fish" },
    { kanji: "天", reading: "てん", english: "heaven" },
    { kanji: "空", reading: "そら", english: "sky" },
    { kanji: "山", reading: "やま", english: "mountain" },
    { kanji: "雨", reading: "あめ", english: "rain" },
    { kanji: "電", reading: "でん", english: "electricity" },
    { kanji: "車", reading: "くるま", english: "car" },
    { kanji: "語", reading: "かたる", english: "language" },
    { kanji: "耳", reading: "みみ", english: "ear" },
    { kanji: "手", reading: "て", english: "hand" },
    { kanji: "足", reading: "あし", english: "foot" },
    { kanji: "目", reading: "め", english: "eye" },
    { kanji: "口", reading: "くち", english: "mouth" },
    { kanji: "名", reading: "な", english: "name" },

    // Places & Directions (17)
    { kanji: "店", reading: "みせ", english: "shop" },
    { kanji: "駅", reading: "えき", english: "station" },
    { kanji: "道", reading: "みち", english: "road" },
    { kanji: "社", reading: "やしろ", english: "shrine" },
    { kanji: "国", reading: "くに", english: "country" },
    { kanji: "外", reading: "そと", english: "outside" },
    { kanji: "学", reading: "まなぶ", english: "to study" },
    { kanji: "校", reading: "こう", english: "school" },
    { kanji: "上", reading: "うえ", english: "above" },
    { kanji: "下", reading: "した", english: "below" },
    { kanji: "中", reading: "なか", english: "inside" },
    { kanji: "北", reading: "きた", english: "north" },
    { kanji: "南", reading: "みなみ", english: "south" },
    { kanji: "東", reading: "ひがし", english: "east" },
    { kanji: "西", reading: "にし", english: "west" },
    { kanji: "右", reading: "みぎ", english: "right" },
    { kanji: "左", reading: "ひだり", english: "left" },

    // Verbs (12)
    { kanji: "見", reading: "みる", english: "to see" },
    { kanji: "聞", reading: "きく", english: "to hear" },
    { kanji: "書", reading: "かく", english: "to write" },
    { kanji: "読", reading: "よむ", english: "to read" },
    { kanji: "話", reading: "はなす", english: "to speak" },
    { kanji: "買", reading: "かう", english: "to buy" },
    { kanji: "行", reading: "いく", english: "to go" },
    { kanji: "出", reading: "でる", english: "to exit" },
    { kanji: "入", reading: "はいる", english: "to enter" },
    { kanji: "休", reading: "やすむ", english: "to rest" },
    { kanji: "食", reading: "たべる", english: "to eat" },
    { kanji: "飲", reading: "のむ", english: "to drink" },

    // Adjectives (8)
    { kanji: "多", reading: "おおい", english: "many" },
    { kanji: "少", reading: "すくない", english: "few" },
    { kanji: "古", reading: "ふるい", english: "old" },
    { kanji: "新", reading: "あたらしい", english: "new" },
    { kanji: "大", reading: "おおきい", english: "big" },
    { kanji: "小", reading: "ちいさい", english: "small" },
    { kanji: "安", reading: "やすい", english: "cheap" },
    { kanji: "高", reading: "たかい", english: "tall" },
  ],
  N4: [
    {
      kanji: "万",
      reading: "まん",
      english: "ten thousand",
      example: "一万円（いちまんえん）",
    },
    {
      kanji: "億",
      reading: "おく",
      english: "hundred million",
      example: "一億人（いちおくにん）",
    },
  ],
  N3: [
    { kanji: "経済", reading: "けいざい", english: "economy" },
    { kanji: "政治", reading: "せいじ", english: "politics" },
    { kanji: "社会", reading: "しゃかい", english: "society" },
  ],
  N2: [
    { kanji: "環境", reading: "かんきょう", english: "environment" },
    { kanji: "技術", reading: "ぎじゅつ", english: "technology" },
  ],
  N1: [{ kanji: "哲学", reading: "てつがく", english: "philosophy" }],
};


